/// <reference types="@sveltejs/kit" />
/// <reference no-default-lib="true"/>
/// <reference lib="esnext" />
/// <reference lib="webworker" />

import { build, files, version } from '$service-worker';

const sw = self as unknown as ServiceWorkerGlobalScope;
const CACHE_NAME = `ear-trainer-${version}`;

// Assets generated by the build + static files
const ASSETS = [...build, ...files];

sw.addEventListener('install', (event) => {
	event.waitUntil(
		caches.open(CACHE_NAME).then((cache) => cache.addAll(ASSETS))
	);
	// Don't skipWaiting — let the new SW wait until all tabs close.
	// This prevents cache/asset mismatch that causes reload loops.
});

sw.addEventListener('activate', (event) => {
	event.waitUntil(
		caches.keys().then((keys) =>
			Promise.all(
				keys
					.filter((key) => key !== CACHE_NAME)
					.map((key) => caches.delete(key))
			)
		)
	);
	// Claim clients so the new SW serves the next navigation (after user's own refresh)
	sw.clients.claim();
});

sw.addEventListener('fetch', (event) => {
	if (event.request.method !== 'GET') return;

	const url = new URL(event.request.url);

	// Skip cross-origin requests
	if (url.origin !== location.origin) return;

	// Navigation requests (HTML): network-first so deploys are picked up immediately.
	// Only fall back to cache if offline.
	if (event.request.mode === 'navigate') {
		event.respondWith(
			fetch(event.request)
				.then((response) => {
					// Cache the fresh navigation response
					const clone = response.clone();
					caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
					return response;
				})
				.catch(() =>
					// Offline fallback: serve cached version
					caches.match(event.request).then((cached) => cached || caches.match('/'))
				)
		);
		return;
	}

	// Sub-resources (JS, CSS, images): cache-first.
	// SvelteKit build assets have content hashes in filenames, so cached = correct.
	event.respondWith(
		caches.match(event.request).then((cached) => {
			if (cached) return cached;

			return fetch(event.request).then((response) => {
				if (!response.ok) return response;

				const clone = response.clone();
				caches.open(CACHE_NAME).then((cache) => cache.put(event.request, clone));
				return response;
			});
		})
	);
});

// Listen for messages from the app (e.g. "skip waiting" prompt)
sw.addEventListener('message', (event) => {
	if (event.data?.type === 'SKIP_WAITING') {
		sw.skipWaiting();
	}
});
